### ISSUE TITLE
export KEY=""" causes a segfault after raising the unclosed quote error is detected error.

### ISSUE THREAD

**Issue by davidwkw** [nwhean/42_core_minishell#51] opened 2022-01-20 03:54 UTC

**Comment by nwhean** [comment] 2022-01-20 05:11
Resolved in commit 2fe5ffa4b7f093212eb6ed630c1f3096384e283b.

This is caused by ptree equals to NULL if there is unclose quote or unclosed bracket. Such lines now causes $? = 1.

**Closed by nwhean** 2022-01-20 05:11 UTC
